backend:
  name: github
  repo: wmadfaa/personal-website
  branch: main
  commit_messages:
    create: "Create {{collection}} “{{slug}}”"
    update: "Update {{collection}} “{{slug}}”"
    delete: "Delete {{collection}} “{{slug}}”"
    uploadMedia: "[skip ci] Upload “{{path}}”"
    deleteMedia: "[skip ci] Delete “{{path}}”"

media_folder: static/img
public_folder: /img

collections:
  - name: experiences
    label: Experiences
    folder: "src/data/experiences"
    fields:
      - {
          label: "Category",
          name: "category",
          widget: "hidden",
          default: "experience",
        }
      - { label: "Company", name: "company" }
      - { label: "Position", name: "position" }
      - { label: "Start Date", name: "startDate", widget: "datetime" }
      - { label: "End Date", name: "endDate", widget: "datetime" }
      - {
          label: "Duties and Responsibilities",
          name: "body",
          widget: "markdown",
        }
  - name: educations
    label: Educations
    folder: "src/data/educations"
    fields:
      - {
          label: "Category",
          name: "category",
          widget: "hidden",
          default: "education",
        }
      - { label: "University or School", name: "university" }
      - { label: "Degree", name: "degree" }
      - { label: "Start Date", name: "startDate", widget: "datetime" }
      - { label: "End Date", name: "endDate", widget: "datetime" }
      - { label: "Tasks and Activities", name: "body", widget: "markdown" }
  - name: "pages"
    label: "Pages"
    files:
      - file: "src/data/about-page.md"
        label: "About Page"
        name: "about-page"
        fields:
          [
            {
              label: "Category",
              name: "category",
              widget: "hidden",
              default: "about page",
            },
            {
              label: "SEO",
              name: "SEO",
              widget: "object",
              fields: [{ label: "page title", name: "title" }],
            },
            {
              label: "Hero-Banner section",
              name: "heroBannerSection",
              widget: "object",
              fields:
                [
                  { label: "Role", name: "role" },
                  { label: "Greeting", name: "greeting" },
                  { label: "About me", name: "aboutMe", widget: "text" },
                ],
            },
            {
              label: "Services section",
              name: "servicesSection",
              widget: "object",
              fields:
                [
                  { label: "Title", name: "title" },
                  { label: "Subtitle", name: "subtitle" },
                  {
                    label: "Services",
                    name: "services",
                    widget: "list",
                    fields:
                      [
                        { label: "Title", name: "title" },
                        { label: "Icon", name: "icon" },
                        {
                          label: "Description",
                          name: "description",
                          widget: "text",
                        },
                      ],
                  },
                ],
            },
          ]
      - file: "src/data/contacts-page.md"
        label: "Contact Page"
        name: "contacts-page"
        fields:
          [
            {
              label: "Category",
              name: "category",
              widget: "hidden",
              default: "contacts page",
            },
            {
              label: "SEO",
              name: "SEO",
              widget: "object",
              fields: [{ label: "page title", name: "title" }],
            },
            { label: "Title", name: "title" },
            { label: "Subtitle", name: "subtitle" },
            {
              label: "Contacts",
              name: "contacts",
              widget: "list",
              fields:
                [
                  { label: "Title", name: "title" },
                  { label: "Icon", name: "icon" },
                  { label: "Content", name: "content" },
                ],
            },
          ]
      - file: "src/data/resume-page.md"
        label: "Resume Page"
        name: "resume-page"
        fields:
          [
            {
              label: "Category",
              name: "category",
              widget: "hidden",
              default: "resume page",
            },
            {
              label: "SEO",
              name: "SEO",
              widget: "object",
              fields: [{ label: "page title", name: "title" }],
            },
            {
              label: "Experience",
              name: "experience",
              widget: "object",
              fields:
                [
                  { label: "Title", name: "title", widget: "markdown" },
                  { label: "Subtitle", name: "subtitle" },
                  {
                    label: "Experiences",
                    name: "experiences section",
                    multiple: true,
                    widget: "relation",
                    collection: "experiences",
                    search_fields: [company, position, startDate, endDate],
                    value_field: "company",
                    display_fields: [company],
                  },
                ],
            },
            {
              label: "Education",
              name: "education",
              type: "object",
              fields:
                [
                  { label: "Title", name: "title" },
                  { label: "Subtitle", name: "subtitle" },
                ],
            },
          ]
